# Generated by Django 4.2.7 on 2023-12-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notatka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
                ('tresc', models.TextField()),
                ('utworzono', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
